#!/bin/bash

if [ -z $1 ]
then
	echo "Needs input jpeg" 
	exit 1
fi

if [ -z $2 ]
then
	echo "Needs output json" 
	exit 1
fi
bname=`basename $1 .jpg`

jp2a $1 --size=700x230 --chars=120 > $bname.txt

cat $bname.txt |sed 's/\([0-9]\)/\1\,/g'|sed 's/\(^[0-9]\)/\[\1/g'|sed 's/\([0-9]\)\,$/\1\]\,/g' >$2

echo "Done $2. Retouch in txt editor"

